spring:
  datasource:
    url: jdbc:h2:mem://localhost/~/Study/workspace/springboot-jpa-shop/test
    #url: jdbc:h2:tcp://localhost/~/Study/workspace/springboot-jpa-shop/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
#    show-sql: true


logging:
  level:
    org:
      hibernate:
        SQL: debug
        #type: trace

